spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/batch_test?profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999&rewriteBatchedStatements=true
    url: jdbc:mysql://localhost:3306/batch_test?rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
#        order_inserts: true
#        order_updates: true
#        jdbc:
#          batch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
#        show_sql: true
        default_batch_fetch_size: 1000
#        format_sql: true
    hibernate:
#      use-new-id-generator-mappings: false
      ddl-auto: create
      generate-ddl: true

#logging:
#  level:
#    org:
#      springframework:
#        jdbc: DEBUG