spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: kwanghoon.kim
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
      properties:
      temp:
        use_jdbc_metadata_defaults: false